version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user
hooks:
  AfterInstall:
    - location: aws/code-deploy/scripts/afterInstall.sh
    - runas: ec2-user
  ApplicationStart:
    - location: aws/code-deploy/scripts/applicationStart.sh
    - runas: ec2-user
