version: '3.9'

services:
  web:
    build: .
    command: python main.py
    container_name: cg
    ports: 
      - "5000:5000"
    volumes: 
      - .:/code
    depends_on: 
      - redis
  redis:
    image: redis
    container_name: redis
