version: "3.9"

services:
  backend:
    build: ./server/
    command: python main.py
    container_name: cg_backend
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/code
    depends_on:
      - redis
  client:
    build: ./client/
    command: npm run serve
    container_name: cg_client
    ports:
      - "8080:8080"
    volumes:
      - "./client/:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: redis
